package org.edu.educationalsystem.DAO;

import org.edu.educationalsystem.Domain.Instructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public interface InstructorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    int insert(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    int insertSelective(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    Instructor selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Instructor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table instructor
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Instructor record);
    Instructor selectByID(Instructor instructor);
    List<Instructor> selectAll();
}