package org.edu.educationalsystem.DAO;

import org.edu.educationalsystem.Domain.Instructor;
import org.edu.educationalsystem.Domain.Section;
import org.edu.educationalsystem.Domain.SectionKey;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public interface SectionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(SectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    int insert(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    int insertSelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    Section selectByPrimaryKey(SectionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Section record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table section
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Section record);

}