package org.edu.educationalsystem.DAO;

import org.edu.educationalsystem.Domain.Takes;
import org.edu.educationalsystem.Domain.TakesKey;

import java.util.List;

public interface TakesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(TakesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    int insert(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    int insertSelective(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    Takes selectByPrimaryKey(TakesKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Takes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table takes
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Takes record);

    List<Takes> selectByID(String id);
}