package org.edu.educationalsystem.Domain;

import java.math.BigDecimal;

public class Instructor {
    public Instructor(){}
    public Instructor(String user_name, String user_password){
        this.id=user_name;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column instructor.salary
     *
     * @mbg.generated
     */
    private BigDecimal salary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.ID
     *
     * @return the value of instructor.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.ID
     *
     * @param id the value for instructor.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.name
     *
     * @return the value of instructor.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.name
     *
     * @param name the value for instructor.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.dept_name
     *
     * @return the value of instructor.dept_name
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.dept_name
     *
     * @param deptName the value for instructor.dept_name
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName == null ? null : deptName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column instructor.salary
     *
     * @return the value of instructor.salary
     *
     * @mbg.generated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column instructor.salary
     *
     * @param salary the value for instructor.salary
     *
     * @mbg.generated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }
}