package org.edu.educationalsystem.Domain;

public class Section extends SectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.building
     *
     * @mbg.generated
     */
    private String building;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.room_number
     *
     * @mbg.generated
     */
    private String roomNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.time_slot_id
     *
     * @mbg.generated
     */
    private String timeSlotId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.building
     *
     * @return the value of section.building
     *
     * @mbg.generated
     */
    public String getBuilding() {
        return building;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.building
     *
     * @param building the value for section.building
     *
     * @mbg.generated
     */
    public void setBuilding(String building) {
        this.building = building == null ? null : building.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.room_number
     *
     * @return the value of section.room_number
     *
     * @mbg.generated
     */
    public String getRoomNumber() {
        return roomNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.room_number
     *
     * @param roomNumber the value for section.room_number
     *
     * @mbg.generated
     */
    public void setRoomNumber(String roomNumber) {
        this.roomNumber = roomNumber == null ? null : roomNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.time_slot_id
     *
     * @return the value of section.time_slot_id
     *
     * @mbg.generated
     */
    public String getTimeSlotId() {
        return timeSlotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.time_slot_id
     *
     * @param timeSlotId the value for section.time_slot_id
     *
     * @mbg.generated
     */
    public void setTimeSlotId(String timeSlotId) {
        this.timeSlotId = timeSlotId == null ? null : timeSlotId.trim();
    }
}