package org.edu.educationalsystem.Domain;

public class SectionKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.sec_id
     *
     * @mbg.generated
     */
    private String secId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.semester
     *
     * @mbg.generated
     */
    private String semester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column section.year
     *
     * @mbg.generated
     */
    private Short year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.course_id
     *
     * @return the value of section.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.course_id
     *
     * @param courseId the value for section.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.sec_id
     *
     * @return the value of section.sec_id
     *
     * @mbg.generated
     */
    public String getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.sec_id
     *
     * @param secId the value for section.sec_id
     *
     * @mbg.generated
     */
    public void setSecId(String secId) {
        this.secId = secId == null ? null : secId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.semester
     *
     * @return the value of section.semester
     *
     * @mbg.generated
     */
    public String getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.semester
     *
     * @param semester the value for section.semester
     *
     * @mbg.generated
     */
    public void setSemester(String semester) {
        this.semester = semester == null ? null : semester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column section.year
     *
     * @return the value of section.year
     *
     * @mbg.generated
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column section.year
     *
     * @param year the value for section.year
     *
     * @mbg.generated
     */
    public void setYear(Short year) {
        this.year = year;
    }
}