package org.edu.educationalsystem.Domain;


public class Student {
    public Student(){}
    public Student(String user_name, String user_password){
        this.id=user_name;
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.dept_name
     *
     * @mbg.generated
     */
    private String deptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.tot_cred
     *
     * @mbg.generated
     */
    private Short totCred;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ID
     *
     * @return the value of student.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ID
     *
     * @param id the value for student.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.dept_name
     *
     * @return the value of student.dept_name
     *
     * @mbg.generated
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.dept_name
     *
     * @param deptName the value for student.dept_name
     *
     * @mbg.generated
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.tot_cred
     *
     * @return the value of student.tot_cred
     *
     * @mbg.generated
     */
    public Short getTotCred() {
        return totCred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.tot_cred
     *
     * @param totCred the value for student.tot_cred
     *
     * @mbg.generated
     */
    public void setTotCred(Short totCred) {
        this.totCred = totCred;
    }
}