package org.edu.educationalsystem.Domain;

public class TakesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.course_id
     *
     * @mbg.generated
     */
    private String courseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.sec_id
     *
     * @mbg.generated
     */
    private String secId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.semester
     *
     * @mbg.generated
     */
    private String semester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.year
     *
     * @mbg.generated
     */
    private Short year;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.ID
     *
     * @return the value of takes.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.ID
     *
     * @param id the value for takes.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.course_id
     *
     * @return the value of takes.course_id
     *
     * @mbg.generated
     */
    public String getCourseId() {
        return courseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.course_id
     *
     * @param courseId the value for takes.course_id
     *
     * @mbg.generated
     */
    public void setCourseId(String courseId) {
        this.courseId = courseId == null ? null : courseId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.sec_id
     *
     * @return the value of takes.sec_id
     *
     * @mbg.generated
     */
    public String getSecId() {
        return secId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.sec_id
     *
     * @param secId the value for takes.sec_id
     *
     * @mbg.generated
     */
    public void setSecId(String secId) {
        this.secId = secId == null ? null : secId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.semester
     *
     * @return the value of takes.semester
     *
     * @mbg.generated
     */
    public String getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.semester
     *
     * @param semester the value for takes.semester
     *
     * @mbg.generated
     */
    public void setSemester(String semester) {
        this.semester = semester == null ? null : semester.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.year
     *
     * @return the value of takes.year
     *
     * @mbg.generated
     */
    public Short getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.year
     *
     * @param year the value for takes.year
     *
     * @mbg.generated
     */
    public void setYear(Short year) {
        this.year = year;
    }
}