package org.edu.educationalsystem.Domain;

public class Takes extends TakesKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column takes.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column takes.grade
     *
     * @return the value of takes.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column takes.grade
     *
     * @param grade the value for takes.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade == null ? null : grade.trim();
    }
}